const endpoints = {
  LOGIN: 'accounts/login/',
  LOGOUT: 'accounts/logout/',
  PROFILE: 'accounts/profile/',
  USER: 'accounts/user/',
  CHANGE_PASS: 'accounts/change-password/',
  RESET_PASS: 'accounts/reset-password/',
  RESET_PASS_CONFIRM: 'accounts/reset-password/confirm/',
  USERS: 'accounts/users/',
  PENDING_USERS: 'accounts/pending-users/',
  SSLPAYMENT_USERS: 'payments/users/',
  SSLPAYMENT: 'payments/initiate/',
  SSLPAYMENT_SUCCESS: 'payments/success/',
  SSLPAYMENT_FAIL: 'payments/fail/',
  SSLPAYMENT_CANCEL: 'payments/cancel/',
  SSLPAYMENT_IPN: 'payments/ipn/',
  MEMBERSHIP_CLAIMS: 'accounts/membership-claims/',
  CREATE_MEMBERSHIP_CLAIM: 'accounts/membership-claim/',
  PROFILES: 'accounts/profiles/',
  BASIC_PROFILE: 'accounts/basic-profile/',
  REGISTER: 'accounts/create/users/',
  REFERRALS: 'accounts/referrals/create/',
  CREATE_SKILL: 'accounts/profile/create/skills/',
  SKILL: 'accounts/profile/skills/',
  CREATE_ACADEMIC: 'accounts/profile/create/academic-histories/',
  ACADEMIC: 'accounts/profile/academic-histories/',
  CREATE_EXPERIENCE: 'accounts/profile/create/work-experiences/',
  EXPERIENCE: 'accounts/profile/work-experiences/',
  MANAGE_ADMINS: 'accounts/make-admin/',
  REMOVE_ADMIN: 'accounts/remove-admin/',
  SET_ROLE: 'accounts/set-role/',

  BLOGS: 'blogs/',
  BLOG_CREATE: 'blogs/create/',
  COMMENTS: 'blogs/comments/',

  EVENTS: 'events/',

  MAILS: 'mails/',
  SYSTEM_MAILS: 'mails/system/',
  USER_MAILS: 'mails/user/',
  ADMIN_SEND_MAILS: 'mails/admin-send/',
  USER_SEND_MAIL: 'mails/send/',
  MY_SENT_MAILS: 'mails/sent-mails/',

  CARDS: 'cards/',
};
export default endpoints;
